INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (4, 246, 'Banco ABC Brasil S.A. ', 'http://www.abcbrasil.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (5, 356, 'Banco ABN AMRO Real S.A. ', 'http://www.abnamro.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (6, 25, 'Banco Alfa S.A. ', 'http://www.bancoalfa.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (7, 641, 'Banco Alvorada S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (8, null, 'Banco American Express S.A. ', 'http://www.aexp.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (9, 29, 'Banco Banerj S.A. ', 'http://www.banerj.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (10, 38, 'Banco Banestado S.A. ', 'http://www.banestado.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (11, 740, 'Banco Barclays S.A. ', 'http://www.barclays.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (12, 107, 'Banco BBM S.A. ', 'http://www.bbmbank.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (13, 31, 'Banco Beg S.A. ', 'http://www.itau.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (14, 36, 'Banco Bem S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (15, 394, 'Banco BMC S.A. ', 'http://www.bmc.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (16, 318, 'Banco BMG S.A. ', 'http://www.bancobmg.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (17, 752, 'Banco BNP Paribas Brasil S.A. ', 'http://www.bnpparibas.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (18, 248, 'Banco Boavista Interatlântico S.A. ', 'não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (19, 237, 'Banco Bradesco S.A. ', 'http://www.bradesco.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (20, 225, 'Banco Brascan S.A. ', 'http://www.bancobrascan.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (21, 263, 'Banco Cacique S.A. ', 'http://www.bancocacique.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (22, 222, 'Banco Calyon Brasil S.A. ', 'http://www.calyon.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (23, 40, 'Banco Cargill S.A. ', 'http://www.bancocargill.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (24, 745, 'Banco Citibank S.A. ', 'http://www.citibank.com/brasil ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (25, 215, 'Banco Comercial e de Investimento Sudameris S.A. ', 'Não possui site');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (26, 756, 'Banco Cooperativo do Brasil S.A. - BANCOOB ', 'http://www.bancoob.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (27, 748, 'Banco Cooperativo Sicredi S.A. - BANSICREDI ', 'http://www.bansicredi.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (28, 505, 'Banco Credit Suisse (Brasil) S.A. ', 'http://www.csfb.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (29, 229, 'Banco Cruzeiro do Sul S.A. ', 'http://www.bcsul.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (30, 3, 'Banco da Amazônia S.A. ', 'http://www.bancoamazonia.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (31, 707, 'Banco Daycoval S.A. ', 'http://www.daycoval.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (32, null, 'Banco de Lage Landen Brasil S.A. ', 'http://www.delagelanden.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (33, 24, 'Banco de Pernambuco S.A. - BANDEPE ', 'http://www.bandepe.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (34, 456, 'Banco de Tokyo-Mitsubishi Brasil S.A. ', 'http://www.btm.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (35, 214, 'Banco Dibens S.A. ', 'http://www.bancodibens.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (36, 1, 'Banco do Brasil S.A. ', 'http://www.bb.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (37, 27, 'Banco do Estado de Santa Catarina S.A. ', 'http://www.besc.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (38, 33, 'Banco do Estado de São Paulo S.A. - Banespa ', 'http://www.banespa.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (39, 47, 'Banco do Estado de Sergipe S.A. ', 'http://www.banese.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (40, 37, 'Banco do Estado do Pará S.A. ', 'http://www.banparanet.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (41, 41, 'Banco do Estado do Rio Grande do Sul S.A. ', 'http://www.banrisul.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (42, 4, 'Banco do Nordeste do Brasil S.A. ', 'http://www.banconordeste.gov.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (43, 265, 'Banco Fator S.A. ', 'http://www.bancofator.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (44, null, 'Banco Fiat S.A. ', 'http://www.bancofiat.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (45, 224, 'Banco Fibra S.A. ', 'http://www.bancofibra.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (46, 175, 'Banco Finasa S.A. ', 'não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (47, 252, 'Banco Fininvest S.A. ', 'http://www.fininvest.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (48, 233, 'Banco GE Capital S.A. ', 'http://www.bancoge.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (49, null, 'Banco General Motors S.A. ', 'http://www.bancogm.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (50, 734, 'Banco Gerdau S.A. ', 'http://www.bancogerdau.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (51, 612, 'Banco Guanabara S.A. ', 'não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (52, 63, 'Banco Ibi S.A. Banco Múltiplo ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (53, 604, 'Banco Industrial do Brasil S.A. ', 'http://www.bancoindustrial.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (54, 320, 'Banco Industrial e Comercial S.A. ', 'http://www.bicbanco.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (55, 653, 'Banco Indusval S.A. ', 'http://www.indusval.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (56, 630, 'Banco Intercap S.A. ', 'http://www.intercap.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (57, 249, 'Banco Investcred Unibanco S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (58, 48, 'Banco Itaú BBA S.A. ', 'http://www.itaubba.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (59, 652, 'Banco Itaú Holding Financeira S.A. ', 'http://www.itau.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (60, 341, 'Banco Itaú S.A. ', 'http://www.itau.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (61, null, 'Banco Itaucred Financiamentos S.A. ', 'http://www.itaucred.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (62, null, 'Banco Itausaga S.A. ', 'http://www.itau.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (63, 376, 'Banco J. P. Morgan S.A. ', 'http://www.jpmorgan.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (64, 74, 'Banco J. Safra S.A. ', 'http://www.jsafra.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (65, 757, 'Banco KEB do Brasil S.A. ', 'não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (66, 600, 'Banco Luso Brasileiro S.A. ', 'http://www.lusobrasileiro.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (67, 392, 'Banco Mercantil de São Paulo S.A. ', 'não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (68, 389, 'Banco Mercantil do Brasil S.A. ', 'http://www.mercantil.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (69, 755, 'Banco Merrill Lynch de Investimentos S.A. ', 'http://www.ml.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (70, 151, 'Banco Nossa Caixa S.A. ', 'http://www.nossacaixa.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (71, 45, 'Banco Opportunity S.A. ', 'http://www.opportunity.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (72, 208, 'Banco Pactual S.A. ', 'http://www.pactual.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (73, 623, 'Banco Panamericano S.A. ', 'http://www.panamericano.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (74, 611, 'Banco Paulista S.A. ', 'http://www.bancopaulista.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (75, 643, 'Banco Pine S.A. ', 'http://www.bancopine.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (76, 638, 'Banco Prosper S.A. ', 'http://www.bancoprosper.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (77, 747, 'Banco Rabobank International Brasil S.A. ', 'http://www.rabobank.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (78, 633, 'Banco Rendimento S.A. ', 'http://www.rendimento.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (79, 72, 'Banco Rural Mais S.A. ', 'http://www.rural.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (80, 453, 'Banco Rural S.A. ', 'http://www.rural.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (81, 422, 'Banco Safra S.A. ', 'http://www.safra.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (82, 353, 'Banco Santander Brasil S.A. ', 'http://www.santander.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (83, 8, 'Banco Santander Meridional S.A. ', 'http://www.meridional.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (84, 351, 'Banco Santander S.A. ', 'http://www.santander.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (85, 250, 'Banco Schahin S.A. ', 'http://www.bancoschahin.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (86, 749, 'Banco Simples S.A. ', 'http://www.bancosimples.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (87, 366, 'Banco Société Générale Brasil S.A. ', 'http://www.sgbrasil.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (88, 637, 'Banco Sofisa S.A. ', 'http://www.sofisa.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (89, 347, 'Banco Sudameris Brasil S.A. ', 'http://www.sudameris.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (90, 464, 'Banco Sumitomo Mitsui Brasileiro S.A. ', 'http://não%20possue%20site/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (91, 634, 'Banco Triângulo S.A. ', 'http://www.tribanco.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (92, 247, 'Banco UBS S.A. ', 'http://www.ubsw.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (93, 116, 'Banco Único S.A. ', 'http://www.unibanco.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (94, 655, 'Banco Votorantim S.A. ', 'http://www.bancovotorantim.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (95, 610, 'Banco VR S.A. ', 'http://www.vr.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (96, 370, 'Banco WestLB do Brasil S.A. ', 'http://www.westlb.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (97, 21, 'BANESTES S.A. Banco do Estado do Espírito Santo ', 'http://www.banestes.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (98, 719, 'Banif-Banco Internacional do Funchal (Brasil)S.A. ', 'http://www.banif.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (99, 479, 'BankBoston Banco Múltiplo S.A. ', 'http://www.bankboston.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (100, 744, 'BankBoston N.A. ', 'http://www.bankboston.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (101, null, 'BB Banco Popular do Brasil S.A. ', 'http://www.bancopopulardobrasil.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (102, null, 'BES Investimento do Brasil S.A.-Banco de Investimento ', 'http://www.besinvestimento.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (103, 70, 'BRB - Banco de Brasília S.A. ', 'http://www.brb.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (104, 104, 'Caixa Econômica Federal ', 'http://www.caixa.gov.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (105, 477, 'Citibank N.A. ', 'http://www.citibank.com/brasil ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (106, null, 'Credicard Banco S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (107, 487, 'Deutsche Bank S.A. - Banco Alemão ', 'http://www.deutsche-bank.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (108, 751, 'Dresdner Bank Brasil S.A. - Banco Múltiplo ', 'http://www.drkw.net/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (109, 210, 'Dresdner Bank Lateinamerika Aktiengesellschaft ', 'http://www.dbla.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (110, 62, 'Hipercard Banco Múltiplo S.A. ', 'http://www.banco1.net/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (111, 399, 'HSBC Bank Brasil S.A. - Banco Múltiplo ', 'http://www.hsbc.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (112, 492, 'ING Bank N.V. ', 'http://www.ing.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (113, 488, 'JPMorgan Chase Bank ', 'http://www.jpmorganchase.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (114, 65, 'Lemon Bank Banco Múltiplo S.A. ', 'http://www.lemon.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (115, 409, 'UNIBANCO - União de Bancos Brasileiros S.A. ', 'http://www.unibanco.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (116, 230, 'Unicard Banco Múltiplo S.A. ', 'http://www.unicard.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (117, 654, 'Banco A.J.Renner S.A. ', 'http://www.bancorenner.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (118, 213, 'Banco Arbi S.A. ', 'http://www.arbi.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (119, 739, 'Banco BGN S.A. ', 'http://www.bgn.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (120, 96, 'Banco BM&F de Serviços de Liquidação e Custódia S.A ', 'http://www.bmf.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (121, 218, 'Banco Bonsucesso S.A. ', 'http://www.bancobonsucesso.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (122, null, 'Banco BRJ S.A. ', 'http://www.brjbank.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (123, 44, 'Banco BVA S.A. ', 'http://www.bancobva.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (124, 412, 'Banco Capital S.A. ', 'http://www.bancocapital.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (125, 266, 'Banco Cédula S.A. ', 'http://www.bancocedula.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (126, 241, 'Banco Clássico S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (127, null, 'Banco CNH Capital S.A. ', 'http://www.bancocnh.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (128, 753, 'Banco Comercial Uruguai S.A. ', 'http://www.bancocomercial.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (129, 75, 'Banco CR2 S.A. ', 'Não possui site');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (130, 721, 'Banco Credibel S.A. ', 'http://www.credibel.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (131, null, 'Banco Daimlerchrysler S.A. ', 'http://www.bancodaimlerchrysler.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (132, 300, 'Banco de La Nacion Argentina ', 'http://www.bna.com.ar/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (133, 495, 'Banco de La Provincia de Buenos Aires ', 'http://www.bapro.com.ar/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (134, 494, 'Banco de La Republica Oriental del Uruguay ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (135, 35, 'Banco do Estado do Ceará S.A. - BEC ', 'http://www.bec.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (136, 39, 'Banco do Estado do Piauí S.A. - BEP ', 'http://www.bep.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (137, 743, 'Banco Emblema S.A. ', 'http://www.bancoemblema.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (138, 626, 'Banco Ficsa S.A. ', 'http://www.ficsa.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (139, null, 'Banco Ford S.A. ', 'http://www.bancoford.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (140, null, 'Banco Honda S.A. ', 'http://www.bancohonda.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (141, null, 'Banco IBM S.A. ', 'http://www.ibm.com/br/financing/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (142, 217, 'Banco John Deere S.A. ', 'http://www.johndeere.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (143, 212, 'Banco Matone S.A. ', 'http://www.bancomatone.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (144, 243, 'Banco Máxima S.A. ', 'http://www.bancomaxima.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (145, null, 'Banco Maxinvest S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (146, 746, 'Banco Modal S.A. ', 'http://www.bancomodal.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (147, null, 'Banco Moneo S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (148, 738, 'Banco Morada S.A. ', 'http://www.bancomorada.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (149, 66, 'Banco Morgan Stanley Dean Witter S.A. ', 'http://www.morganstanley.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (150, null, 'Banco Ourinvest S.A. ', 'http://www.ourinvest.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (151, 613, 'Banco Pecúnia S.A. ', 'http://www.bancopecunia.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (152, 724, 'Banco Porto Seguro S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (153, 735, 'Banco Pottencial S.A. ', 'http://www.pottencial.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (154, null, 'Banco PSA Finance Brasil S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (155, 741, 'Banco Ribeirão Preto S.A. ', 'http://www.brp.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (156, null, 'Banco Rodobens S.A. ', 'http://www.rodobens.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (157, null, 'Banco Toyota do Brasil S.A. ', 'http://www.bancotoyota.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (158, null, 'Banco Tricury S.A. ', 'http://www.tricury.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (159, null, 'Banco Volkswagen S.A. ', 'http://www.bancovw.com.br/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (160, null, 'Banco Volvo (Brasil) S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (161, null, 'BPN Brasil Banco Mútiplo S.A. ', 'Não possui site ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (162, 64, 'Goldman Sachs do Brasil Banco Múltiplo S.A. ', 'http://www.goldmansachs.com/ ');
INSERT INTO senai_erp.banco (ID, CODIGO, NOME, URL) VALUES (163, 254, 'Paraná Banco S.A. ', 'http://www.paranabanco.com.br/ ');
