CREATE TABLE `agencia_banco` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CEP_ID` int(10) unsigned NOT NULL,
  `BANCO_ID` int(10) unsigned NOT NULL,
  `CODIGO` int(10) unsigned DEFAULT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `ENDERECO` varchar(100) DEFAULT NULL,
  `TELEFONE` varchar(10) DEFAULT NULL,
  `GERENTE` varchar(30) DEFAULT NULL,
  `CONTATO` varchar(30) DEFAULT NULL,
  `OBS` text,
  PRIMARY KEY (`ID`),
  KEY `FK_BANCO_AGENCIA` (`BANCO_ID`),
  KEY `FK_CEP_AGENCIA_BANCO` (`CEP_ID`)
);
CREATE TABLE `banco` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CODIGO` int(10) unsigned DEFAULT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `URL` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `cargo` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  `SALARIO` double(11,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `cep` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CIDADE_ID` int(10) unsigned NOT NULL,
  `CEP` varchar(8) DEFAULT NULL,
  `COMPLEMENTO` varchar(100) DEFAULT NULL,
  `LOGRADOURO` varchar(100) DEFAULT NULL,
  `BAIRRO` varchar(50) DEFAULT NULL,
  `cidade` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CIDADE_CEP` (`CIDADE_ID`)
);
CREATE TABLE `cfop` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CFOP` int(10) unsigned DEFAULT NULL,
  `DESCRICAO` text,
  `APLICACAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `cidade` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ESTADO_ID` int(10) unsigned NOT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `CODIGO_IBGE` int(10) unsigned DEFAULT NULL,
  `nome2` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ESTADO_CIDADE` (`ESTADO_ID`)
);
CREATE TABLE `cliente` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `SITUACAO_FOR_CLI_ID` int(10) unsigned NOT NULL,
  `ID_EMPRESA` int(10) unsigned NOT NULL,
  `NOME` varchar(150) DEFAULT NULL,
  `CPF_CNPJ` varchar(14) DEFAULT NULL,
  `RG` varchar(20) DEFAULT NULL,
  `ORGAO_RG` varchar(10) DEFAULT NULL,
  `INSCRICAO_ESTADUAL` varchar(30) DEFAULT NULL,
  `INSCRICAO_MUNICIPAL` varchar(30) DEFAULT NULL,
  `DESDE` date DEFAULT NULL,
  `TIPO_PESSOA` char(1) DEFAULT NULL,
  `EXCLUIDO` char(1) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EMPRESA_CLIENTE` (`ID_EMPRESA`),
  KEY `FK_SITUACAO_CLIENTE` (`SITUACAO_FOR_CLI_ID`)
);

CREATE TABLE `colaborador` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NIVEL_FORMACAO_ID` int(10) unsigned NOT NULL,
  `TIPO_COLABORADOR_ID` int(10) unsigned NOT NULL,
  `CARGO_ID` int(10) unsigned NOT NULL,
  `ID_SETOR` int(10) unsigned NOT NULL,
  `NOME` varchar(150) DEFAULT NULL,
  `CPF` varchar(11) DEFAULT NULL,
  `RG` varchar(20) DEFAULT NULL,
  `ORGAO_RG` varchar(10) DEFAULT NULL,
  `DATA_NASCIMENTO` date DEFAULT NULL,
  `TIPO_SANGUINEO` varchar(5) DEFAULT NULL,
  `FOTO_34` varchar(255) DEFAULT NULL,
  `EXCLUIDO` char(1) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_COLABORADOR_SETOR` (`ID_SETOR`),
  KEY `FK_CARGO_COLABORADOR` (`CARGO_ID`),
  KEY `FK_TIPO_COLABORADOR` (`TIPO_COLABORADOR_ID`),
  KEY `FK_NIVEL_FORMACAO_COLABORADOR` (`NIVEL_FORMACAO_ID`)
);
CREATE TABLE `colaborador_relacionamento` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `TIPO_RELACIONAMENTO_ID` int(10) unsigned NOT NULL,
  `COLABORADOR_ID` int(10) unsigned NOT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_COLABORADOR_RELACIONAMENTO` (`COLABORADOR_ID`),
  KEY `FK_TIPO_COLABORADOR_RELACIONAMENTO` (`TIPO_RELACIONAMENTO_ID`)
);
CREATE TABLE `contato` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EMPRESA_ID` int(10) unsigned DEFAULT NULL,
  `COLABORADOR_ID` int(10) unsigned DEFAULT NULL,
  `CLIENTE_ID` int(10) unsigned DEFAULT NULL,
  `FORNECEDOR_ID` int(10) unsigned DEFAULT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `DONO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_FORNECEDOR_CONTATO` (`FORNECEDOR_ID`),
  KEY `FK_CLIENTE_CONTATO` (`CLIENTE_ID`),
  KEY `FK_COLABORADOR_CONTATO` (`COLABORADOR_ID`),
  KEY `FK_EMPRESA_CONTATO` (`EMPRESA_ID`)
);

CREATE TABLE `contato_email` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `TIPO_EMAIL_ID` int(10) unsigned NOT NULL,
  `CONTATO_ID` int(10) unsigned NOT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CONTATO_EMAIL` (`CONTATO_ID`),
  KEY `FK_TIPO_EMAIL_CONTATO` (`TIPO_EMAIL_ID`)
);
CREATE TABLE `contato_telefone` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `TIPO_TELEFONE_ID` int(10) unsigned NOT NULL,
  `CONTATO_ID` int(10) unsigned NOT NULL,
  `TELEFONE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CONTATO_EMAIL` (`CONTATO_ID`),
  KEY `FK_TIPO_TELEFONE_CONTATO` (`TIPO_TELEFONE_ID`)
);
CREATE TABLE `convenio` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_EMPRESA` int(10) unsigned NOT NULL,
  `NOME` varchar(100) DEFAULT NULL,
  `DESCRICAO` text,
  `DESCONTO` double(11,2) DEFAULT NULL,
  `DATA_VENCIMENTO` date DEFAULT NULL,
  `ENDERECO` varchar(250) DEFAULT NULL,
  `CONTATO` varchar(30) DEFAULT NULL,
  `TELEFONE` varchar(10) DEFAULT NULL,
  `EXCLUIDO` char(1) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EMPRESA_CONVENIO` (`ID_EMPRESA`)
);
CREATE TABLE `empresa` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EMPRESA_ID` int(10) unsigned NOT NULL,
  `RAZAO_SOCIAL` varchar(150) DEFAULT NULL,
  `NOME_FANTASIA` varchar(150) DEFAULT NULL,
  `CNPJ` varchar(14) DEFAULT NULL,
  `INSCRICAO_ESTADUAL` varchar(30) DEFAULT NULL,
  `INSCRICAO_MUNICIPAL` varchar(30) DEFAULT NULL,
  `MATRIZ_FILIAL` char(1) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EMPRESA_FILIAL` (`EMPRESA_ID`)
);

CREATE TABLE `empresa_produto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EMPRESA_ID` int(10) unsigned NOT NULL,
  `PRODUTO_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUTO_EMPRESA` (`PRODUTO_ID`),
  KEY `FK_EMPRESA_PRODUTO` (`EMPRESA_ID`)
);
CREATE TABLE `endereco` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EMPRESA_ID` int(10) unsigned DEFAULT NULL,
  `COLABORADOR_ID` int(10) unsigned DEFAULT NULL,
  `FORNECEDOR_ID` int(10) unsigned DEFAULT NULL,
  `CLIENTE_ID` int(10) unsigned DEFAULT NULL,
  `TIPO_ENDERECO_ID` int(10) unsigned NOT NULL,
  `CEP_ID` int(10) unsigned NOT NULL,
  `LOGRADOURO` varchar(100) DEFAULT NULL,
  `NUMERO` int(10) unsigned DEFAULT NULL,
  `COMPLEMENTO` varchar(100) DEFAULT NULL,
  `BAIRRO` varchar(50) DEFAULT NULL,
  `DONO` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CEP_ENDERECO` (`CEP_ID`),
  KEY `FK_TIPO_ENDERECO` (`TIPO_ENDERECO_ID`),
  KEY `FK_CLIENTE_ENDERECO` (`CLIENTE_ID`),
  KEY `FK_FORNECEDOR_ENDERECO` (`FORNECEDOR_ID`),
  KEY `FK_COLABORADOR_ENDERECO` (`COLABORADOR_ID`),
  KEY `FK_EMPRESA_ENDERECO` (`EMPRESA_ID`)
);
CREATE TABLE `estado` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PAIS_ID` int(10) unsigned NOT NULL,
  `SIGLA` char(2) DEFAULT NULL,
  `NOME` varchar(50) DEFAULT NULL,
  `CODIGO_IBGE` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PAIS_ESTADO` (`PAIS_ID`)
);
CREATE TABLE `fornecedor` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `SITUACAO_FOR_CLI_ID` int(10) unsigned NOT NULL,
  `TIPO_FORNECEDOR_ID` int(10) unsigned NOT NULL,
  `ID_EMPRESA` int(10) unsigned NOT NULL,
  `NOME` varchar(150) DEFAULT NULL,
  `CPF_CNPJ` varchar(14) DEFAULT NULL,
  `RG` varchar(20) DEFAULT NULL,
  `ORGAO_RG` varchar(10) DEFAULT NULL,
  `INSCRICAO_ESTADAL` varchar(30) DEFAULT NULL,
  `INSCRICAO_MUNICIPAL` varchar(30) DEFAULT NULL,
  `DESDE` date DEFAULT NULL,
  `TIPO_PESSOA` char(1) DEFAULT NULL,
  `EXCLUIDO` char(1) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_EMPRESA_FORNECEDOR` (`ID_EMPRESA`),
  KEY `FK_TIPO_FORNECEDOR` (`TIPO_FORNECEDOR_ID`),
  KEY `FK_SITUACAO_FORNECEDOR` (`SITUACAO_FOR_CLI_ID`)
);
CREATE TABLE `fornecedor_produto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `FORNECEDOR_ID` int(10) unsigned NOT NULL,
  `PRODUTO_ID` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUTO_FORNECEDOR` (`PRODUTO_ID`),
  KEY `FK_FORNECEDOR_PRODUTO` (`FORNECEDOR_ID`)
);
CREATE TABLE `funcao` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DESCRICAO_MENU` varchar(30) DEFAULT NULL,
  `IMAGEM_MENU` varchar(30) DEFAULT NULL,
  `METODO` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `grupo_produto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `indice_economico` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PAIS_ID` int(10) unsigned NOT NULL,
  `SIGLA` varchar(50) DEFAULT NULL,
  `NOME` varchar(50) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`),
  KEY `FK_PAIS_INDICE_ECONOMICO` (`PAIS_ID`)
);
CREATE TABLE `nivel_formacao` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `operadora_cartao` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `BANDEIRA` varchar(30) DEFAULT NULL,
  `NOME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `pais` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CODIGO` int(10) unsigned DEFAULT NULL,
  `NOME_EN` varchar(100) DEFAULT NULL,
  `NOME_PTBR` varchar(100) DEFAULT NULL,
  `SIGLA2` char(2) DEFAULT NULL,
  `SIGLA3` char(3) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `papel` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `papel_funcao` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `FUNCAO_ID` int(10) unsigned NOT NULL,
  `PAPEL_ID` int(10) unsigned NOT NULL,
  `PODE_CONSULTAR` char(1) DEFAULT NULL,
  `PODE_INSERIR` char(1) DEFAULT NULL,
  `PODE_ALTERAR` char(1) DEFAULT NULL,
  `PODE_EXCLUIR` char(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PAPEL_FUNCAO` (`PAPEL_ID`),
  KEY `FK_FUNCAO_PAPEL` (`FUNCAO_ID`)
);
CREATE TABLE `produto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_SUB_GRUPO` int(10) unsigned NOT NULL,
  `ID_UNIDADE` int(10) unsigned NOT NULL,
  `GTIN` char(14) DEFAULT NULL,
  `NOME_PRODUTO` varchar(100) DEFAULT NULL,
  `DESCRICAO` text,
  `DESCRICAO_PDV` varchar(30) DEFAULT NULL,
  `VALOR_COMPRA` double(11,2) DEFAULT NULL,
  `VALOR_VENDA` double(11,2) DEFAULT NULL,
  `QTD_ESTOQUE` double(11,2) DEFAULT NULL,
  `ESTOQUE_MIN` double(11,2) DEFAULT NULL,
  `ESTOQUE_MAX` double(11,2) DEFAULT NULL,
  `EXCLUIDO` char(1) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PRODUTO_UNIDADE` (`ID_UNIDADE`),
  KEY `FK_PRODUTO_SUBGRUPO` (`ID_SUB_GRUPO`)
);
CREATE TABLE `setor` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `EMPRESA_ID` int(10) unsigned NOT NULL,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`),
  KEY `FK_EMPRESA_SETOR` (`EMPRESA_ID`)
);

CREATE TABLE `situacao_for_cli` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `sub_grupo_produto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ID_GRUPO` int(10) unsigned NOT NULL,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`),
  KEY `FK_SUB_GRUPO_GRUPO` (`ID_GRUPO`)
);
CREATE TABLE `tipo_colaborador` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `tipo_email` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `tipo_endereco` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `tipo_fornecedor` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `tipo_relacionamento` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);
CREATE TABLE `tipo_telefone` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(20) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `unidade_produto` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NOME` varchar(10) DEFAULT NULL,
  `DESCRICAO` text,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `usuario` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PAPEL_ID` int(10) unsigned NOT NULL,
  `COLABORADOR_ID` int(10) unsigned NOT NULL,
  `LOGIN` varchar(20) DEFAULT NULL,
  `SENHA` varchar(20) DEFAULT NULL,
  `DATA_CADASTRO` date DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_COLABORADOR_USUARIO` (`COLABORADOR_ID`),
  KEY `FK_PAPEL_USUARIO` (`PAPEL_ID`)
);
